### ISSUE TITLE
Set-Up Backend

### ISSUE THREAD

**Issue by vazquezea96** [vazquezea96/Survey-Creator-Manager#2]
- [x] Figure out the backend tech stack
- [x] Get the back-end server running locally
- [x] Figure out endpoints/routes we may need
- [x] Figure out the database

**Comment by EMERIC237** [comment]
The Database we are using in "MongoDb"
The backend-Stack is currently MongoDb-Spring( we might need a testing software also)
The backend server is currently working locally. But the Apis still need to be written for communication

**Comment by vazquezea96** [comment]
Awesome. Good stuff!
